### ISSUE TITLE
no matching package named `subtitles-utils` found

### ISSUE THREAD

**Issue by Des-Nerger** [gwen-lg/subtile#1]
```
    Updating git repository `https://github.com/gwen-lg/subparse`
    Updating git repository `https://github.com/gwen-lg/subtile`
    Updating crates.io index
error: no matching package named `subtitles-utils` found
location searched: https://github.com/gwen-lg/subparse?branch=perf#62591c8f
required by package `subparse v0.7.0 (https://github.com/gwen-lg/subparse?branch=perf#62591c8f)`
```

**Comment by gwen-lg** [comment]
Hello @Des-Nerger ,
What you tried to do when to have this ?
I thought I had cleaned up the references to `subtitles-utils`.
This version of subparse is not supposed to be used.

**Comment by Des-Nerger** [comment]
I just saw that your fork of `subparse` is basically the only one that is still maintained, so hoped I could use it...
I added those deps like this:
```
[dependencies.subparse]
git = "https://github.com/gwen-lg/subparse"
branch = "perf"

[dependencies.subtile]
git = "https://github.com/gwen-lg/subtile"
```

**Comment by gwen-lg** [comment]
Ugh, no, my work on `subparse` was basically experimentation.
Projects I am actively working on are `subtile` and derivating (`subtile-ocr` for now).

My objective is to progressively add in `subtile` crate capabilities of `subparse`.
But it's not the case for now.

What's your usage of `subtile` and `subparse` ?

**Comment by Des-Nerger** [comment]
I only wanted to use `subparse`, actually. (To base-on / write tools similar to the alass syncer.) And only added `subtile` because it looked like a dependency for `subparse`. But you seem to rename it from `subtitles-utils`... Never mind. Including patched `nom` was enough for me to get rid of all the warnings caused by the "unmaintained" state of `subparse`: https://github.com/Des-Nerger/rsssync

**Comment by gwen-lg** [comment]
Ok, subtile is the public version of work tested on subtitles-utils.

In case you are interested, I have updated to perf branch to use published `subtile` crate instead of `subtitle-utils`.
