### ISSUE TITLE
testsuite fails on 32-bit architectures

### ISSUE THREAD

**Issue by jonassmedegaard** [gwen-lg/subtile#2]
Testsuite fails (at least with release v0.1.3, and seems it wasn't addressed for v0.1.4) on 32-bit architectures, like this:
```
 95s error[E0277]: the trait bound `u64: ToUsize` is not satisfied
 95s   --> src/vobsub/mpeg2/clock.rs:55:21
 95s    |
 95s 55 |     let hi_p = take(3u64);
 95s    |                ---- ^^^^ the trait `ToUsize` is not implemented for `u64`
 95s    |                |
 95s    |                required by a bound introduced by this call
 95s    |
 95s    = help: the following other types implement trait `ToUsize`:
 95s              u16
 95s              u32
 95s              u8
 95s              usize
 95s note: required by a bound in `nom::complete::take`
 95s   --> /usr/share/cargo/registry/nom-7.1.3/src/bits/complete.rs:38:6
 95s    |
 95s 38 |   C: ToUsize,
 95s    |      ^^^^^^^ required by this bound in `take`
```
Full build log is (for a little while) [here](https://ci.debian.net/packages/r/rust-subtile/testing/armel/45145430/)

**Comment by gwen-lg** [comment]
Thank's for the report.
Can you test the fix in branch https://github.com/gwen-lg/subtile/commits/fix_32bits_build/ before I release a new version ?

**Comment by jonassmedegaard** [comment]
Quoting Gwen Lg (2024-04-12 21:54:48)
> Can you test the fix in branch https://github.com/gwen-lg/subtile/commits/fix_32bits_build/ before I release a new version ?

Certainly.  The package is now released to Debian unstable with your
patch applied, and tests should appear within the next hours or days
here: https://tracker.debian.org/pkg/rust-subtile (in the middle of the
page where right now is listed test results for package version 0.1.4-1,
which should soon switch to version 0.1.4-2 with the patch applied).

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/
 * Sponsorship: https://ko-fi.com/drjones

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
Your patch caused the build on i386 to succeed. armel and armhf build daemons are slower and therefore the queues for them are longer, so uncertain if it affected those as well.

**Comment by gwen-lg** [comment]
I have release a new version (v0.1.5) with the fix.
